
package Vista;
import Control.Empleado;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author justinRm
 */
public class VentanaRegistro extends javax.swing.JDialog {
    DefaultTableModel modelo;
    Map<Integer, Empleado> datos = new HashMap<>(); // Usamos un HashMap con Empleado
    private int idCounter = 1;
    int filaSeleccionada = -1;
 
    public void llenarCampos(String nombre, String apellido, String edad, String categoria) {
        Txtnombre.setText(nombre);
        Txtapellido.setText(apellido);
        Txtedad.setText(edad);
        Txtcategoria.setSelectedItem(categoria);
    }
    public VentanaRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Edad");
        modelo.addColumn("Categoria");
        this.Tabla.setModel(modelo);         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txtnombre = new javax.swing.JTextField();
        Txtapellido = new javax.swing.JTextField();
        Txtedad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txtcategoria = new javax.swing.JComboBox<>();
        Btinsertar = new javax.swing.JButton();
        Btactualizar = new javax.swing.JButton();
        Bteliminar = new javax.swing.JButton();
        Btguardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales de Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Edad:");

        Txtnombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TxtnombreInputMethodTextChanged(evt);
            }
        });
        Txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnombreActionPerformed(evt);
            }
        });
        Txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtnombreKeyTyped(evt);
            }
        });

        Txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtapellidoActionPerformed(evt);
            }
        });
        Txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtapellidoKeyTyped(evt);
            }
        });

        Txtedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtedadActionPerformed(evt);
            }
        });
        Txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtedadKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Categoria:");

        Txtcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auxiliar", "Administrador/a", "Gerente", "Secretaria/o", "Tecnico", "Vendedor", " ", " " }));
        Txtcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcategoriaActionPerformed(evt);
            }
        });

        Btinsertar.setText("INSERTAR");
        Btinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtinsertarActionPerformed(evt);
            }
        });

        Btactualizar.setText("Actualizar");
        Btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtactualizarActionPerformed(evt);
            }
        });

        Bteliminar.setText("ELIMINAR");
        Bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BteliminarActionPerformed(evt);
            }
        });

        Btguardar.setText("Guardar");
        Btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(Txtapellido)
                            .addComponent(Txtedad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bteliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(Btactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btinsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btinsertar))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Btactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btguardar)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bteliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Rawawe.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Edad", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtinsertarActionPerformed
    String nombre = Txtnombre.getText();
    String apellido = Txtapellido.getText();
    String edadStr = Txtedad.getText(); // Obtener el valor como cadena
    String categoria = (String) Txtcategoria.getSelectedItem();
    
    int edad; // Variable para almacenar la edad convertida
    
    try {
        edad = Integer.parseInt(edadStr); // Intentar convertir la cadena en un entero
    } catch (NumberFormatException e) {
        // Manejar el caso en que no se pueda convertir a un número
        JOptionPane.showMessageDialog(this, "La edad debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Salir del método para evitar más procesamiento incorrecto
    }

    Empleado empleado = new Empleado(nombre, apellido, edad, categoria);
    datos.put(idCounter, empleado);
    
    String apellid;
    
    
    modelo.addRow(new Object[]{nombre, apellido, edad, categoria});

    Txtnombre.setText("");
    Txtapellido.setText("");
    Txtedad.setText("");

    idCounter++;
    }//GEN-LAST:event_BtinsertarActionPerformed

    private void BteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BteliminarActionPerformed
        int fila = Tabla.getSelectedRow();
        if (fila >= 0) {
            int empleadoId = (int) datos.keySet().toArray()[fila];
            modelo.removeRow(fila);
            datos.remove(empleadoId);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccionar la fila a eliminar");
        }
    }//GEN-LAST:event_BteliminarActionPerformed

    private void TxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnombreActionPerformed

    }//GEN-LAST:event_TxtnombreActionPerformed

    private void TxtcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcategoriaActionPerformed


    
    private void BtactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtactualizarActionPerformed
        if (filaSeleccionada >= 0) {
            int empleadoId = (int) datos.keySet().toArray()[filaSeleccionada];
            Empleado empleado = datos.get(empleadoId);

            empleado.setNombre(Txtnombre.getText());
            empleado.setApellido(Txtapellido.getText());
            empleado.setEdad(Integer.parseInt(Txtedad.getText()));
            empleado.setCategoria((String) Txtcategoria.getSelectedItem());

            modelo.setValueAt(empleado.getNombre(), filaSeleccionada, 0);
            modelo.setValueAt(empleado.getApellido(), filaSeleccionada, 1);
            modelo.setValueAt(empleado.getEdad(), filaSeleccionada, 2);
            modelo.setValueAt(empleado.getCategoria(), filaSeleccionada, 3);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtactualizarActionPerformed

    private void BtguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtguardarActionPerformed
    guardarDatosEnCSV("empleados.csv");
    }//GEN-LAST:event_BtguardarActionPerformed

    private void TxtedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtedadActionPerformed

    private void TxtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtapellidoActionPerformed

    private void TxtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtapellidoKeyTyped
        char c = evt.getKeyChar();

                if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_BACK_SPACE)) {
                    // Si el carácter no es una letra, un espacio o la tecla Backspace, consume el evento
                    evt.consume();
                }
    }//GEN-LAST:event_TxtapellidoKeyTyped

    private void TxtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtedadKeyTyped
char c = evt.getKeyChar();
        String texto = Txtedad.getText();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || texto.length() >= 2) {
            // Si el carácter no es un dígito o la tecla Backspace, o el texto ya tiene 10 caracteres, consume el evento
            evt.consume();
        } 
        
    }//GEN-LAST:event_TxtedadKeyTyped

    private void TxtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtnombreKeyTyped
char c = evt.getKeyChar();

        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_BACK_SPACE)) {
            // Si el carácter no es una letra, un espacio o la tecla Backspace, consume el evento
            evt.consume();
        }
    }//GEN-LAST:event_TxtnombreKeyTyped

    private void TxtnombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TxtnombreInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnombreInputMethodTextChanged
    // Método para establecer la referencia a la ventana Almacenamiento


private void guardarDatosEnCSV(String archivoCSV) {
    try {
        FileWriter csvWriter = new FileWriter(archivoCSV);
        csvWriter.append("Nombre,Apellido,Edad,Categoria\n");

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombre = (String) modelo.getValueAt(i, 0);
            String apellido = (String) modelo.getValueAt(i, 1);
            int edad = (int) modelo.getValueAt(i, 2);
            String categoria = (String) modelo.getValueAt(i, 3);

            csvWriter.append(nombre).append(",").append(apellido).append(",").append(String.valueOf(edad)).append(",").append(categoria).append("\n");
        }

        csvWriter.flush();
        csvWriter.close();

        JOptionPane.showMessageDialog(this, "Datos guardados correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar los datos", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistro dialog = new VentanaRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btactualizar;
    private javax.swing.JButton Bteliminar;
    private javax.swing.JButton Btguardar;
    private javax.swing.JButton Btinsertar;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Txtapellido;
    private javax.swing.JComboBox<String> Txtcategoria;
    private javax.swing.JTextField Txtedad;
    private javax.swing.JTextField Txtnombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

